version: '3.8'

services:
  # WhatsApp API Instance 1 (Users 1-50)
  wa-api-1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - HEADLESS=true
      - INSTANCE_ID=1
      - USER_RANGE=1-50
    volumes:
      - ./sessions-1:/app/sessions
      - ./data-1:/app/data
    networks:
      wa_network:
        ipv4_address: 172.20.0.11
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # WhatsApp API Instance 2 (Users 51-100)
  wa-api-2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - HEADLESS=true
      - INSTANCE_ID=2
      - USER_RANGE=51-100
    volumes:
      - ./sessions-2:/app/sessions
      - ./data-2:/app/data
    networks:
      wa_network:
        ipv4_address: 172.20.0.12
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # WhatsApp API Instance 3 (Users 101-150)
  wa-api-3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - HEADLESS=true
      - INSTANCE_ID=3
      - USER_RANGE=101-150
    volumes:
      - ./sessions-3:/app/sessions
      - ./data-3:/app/data
    networks:
      wa_network:
        ipv4_address: 172.20.0.13
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # WhatsApp API Instance 4 (Users 151-200)
  wa-api-4:
    build: .
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - HEADLESS=true
      - INSTANCE_ID=4
      - USER_RANGE=151-200
    volumes:
      - ./sessions-4:/app/sessions
      - ./data-4:/app/data
    networks:
      wa_network:
        ipv4_address: 172.20.0.14
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wa-api-1
      - wa-api-2
      - wa-api-3
      - wa-api-4
    networks:
      wa_network:
        ipv4_address: 172.20.0.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # Watchtower for auto-updates (optional)
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: unless-stopped

networks:
  wa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  sessions-1:
  sessions-2:
  sessions-3:
  sessions-4:
  data-1:
  data-2:
  data-3:
  data-4: